model_name: "Bailey Marie"
welcome_message: "ü•Ä Hi I'm Bailey üíã"
bio: "Hot wife. I love to do custom content! Let me know how I can please you ‚ô•Ô∏è"
background_image: "background.png"
gumroad_link: "https://onlyfans.com/bailey_marie/c2"
#mailchimp_action_url: "https://github.us21.list-manage.com/subscribe/post?u=e8131dd97e9e243bc448e3941&amp;id=8734494c97&amp;f_id=00a0e3e6f0"
#mailchimp_hidden_name: "YOUR_MAILCHIMP_HIDDEN_FIELD_NAME"
#social_platforms:
 # - name: "Instagram"
 #   url: "https://www.instagram.com/_gabi.ryu_/"
 #   icon: "instagram"
  #- name: "TikTok"
   # url: "https://tiktok.com/@your_username_here"
    #icon: "tiktok"
  #- name: "Reddit"
   # url: "https://reddit.com/u/your_username_here"
   # icon: "reddit"
  #- name: "GitHub"
   # url: "https://github.com/your_username_here"
   # icon: "github"
